#%RAML 1.0 NamedExample
          [
{
	 	 Id : 123,
	 	 productName : “Sweat Shirt”,
	 	 productType : “Clothing”,
	 	 quantiyAvailable : 20,
	 	 pricePerItem : 2500
},
{
	 	 Id : 245,
	 	 productName : “TV”,
	 	 productType : “Television”,
	 	 quantiyAvailable : 40,
	 	 pricePerItem : 150000
},
{
	 	 Id : 123,
	 	 productName : “Stove”,
	 	 productType : “Kitchen appliances”,
	 	 quantiyAvailable : 10,
	 	 pricePerItem : 25200
}
]